name: clickgen
channels:
  - pyg
  - pytorch
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alabaster=0.7.13=pyhd8ed1ab_0
  - babel=2.12.1=pyhd8ed1ab_1
  - blas=1.0=mkl
  - boost=1.74.0=py37h796e4cb_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py37hda87dfa_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py37h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=38.0.1=py37h9ce1e76_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - docutils=0.16=py37h89c1867_3
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.14.1=hc2a2eb6_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.4.0.31=0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py37h06a4308_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py37h295c915_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.5=he0ac6c6_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-base=3.4.3=py37h1058ff1_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.3.0.22=0
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openbabel=3.1.1=py37h6aa62a1_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1u=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.2.0=py37hace64e9_1
  - pixman=0.40.0=h36c2ea0_0
  - pycairo=1.21.0=py37h0afab05_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.0=py37_torch_1.13.0_cu116
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - python=3.7.15=haa1d7c7_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.13.0=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.6=pyhd8ed1ab_0
  - rdkit=2022.03.2=py37hc52db9c_0
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.68=py37h69800bb_1
  - requests=2.28.1=py37h06a4308_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=65.5.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sphinx=5.3.0=pyhd8ed1ab_0
  - sphinx_rtd_theme=1.2.2=pyha770c72_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlalchemy=1.3.24=py37h540881e_1
  - sqlite=3.39.3=h5082296_0
  - swig=4.0.2=hd3c618e_2
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.0=py37_cu116
  - torchvision=0.14.0=py37_cu116
  - tornado=6.2=py37h540881e_0
  - tqdm=4.64.1=py37h06a4308_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - urllib3=1.26.12=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.3.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - astunparse==1.6.3
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blessed==1.19.1
      - cachetools==5.2.0
      - comm==0.1.4
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - fastjsonschema==2.18.0
      - fcd==1.1
      - flatbuffers==22.12.6
      - gast==0.4.0
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - gpustat==1.0.0
      - grpcio==1.51.1
      - guacamol==0.5.4
      - h5py==3.7.0
      - importlib-metadata==5.2.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - jedi==0.19.0
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.8
      - keras==2.11.0
      - libclang==14.0.6
      - markdown==3.4.1
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.7
      - networkx==2.6.3
      - notebook==6.5.5
      - notebook-shim==0.2.3
      - nvidia-ml-py==11.495.46
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pip==23.3.1
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==3.19.6
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyrsistent==0.19.3
      - python-ternary==1.0.8
      - pyzmq==24.0.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - rdkit-pypi==2022.9.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.29.0
      - termcolor==2.1.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - traitlets==5.9.0
      - vina==1.2.5
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.8
      - wrapt==1.14.1
      - zipp==3.11.0
prefix: /root/anaconda3/envs/py37
